version: '3.8'

services:

  kafka:
    image: apache/kafka:4.2.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: broker,controller
      KAFKA_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093,PLAINTEXT_INTERNAL://0.0.0.0:29092
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092,PLAINTEXT_INTERNAL://kafka:29092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_INTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT_INTERNAL
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1

  ksqldb:
    image: confluentinc/ksqldb-server:latest
    depends_on:
      - kafka
    ports:
      - "8088:8088"
    environment:
      KSQL_BOOTSTRAP_SERVERS: kafka:29092
      KSQL_LISTENERS: http://0.0.0.0:8088
      KSQL_KSQL_SERVICE_ID: ksqldb_service

  construction-app:
    build: .
    depends_on:
      - kafka
      - ksqldb
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      EVENT_INTERVAL_MS: 7000

  dbt-pipeline:
    build:
      context: "../../DATA OBSERVABILITY"
      dockerfile: dockerfile.dbt
    depends_on:
      - kafka
      - ksqldb
      - construction-app
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
      KAFKA_TOPIC: site-health-stream
      KAFKA_EXPORT_FILE: site_health_events.json
      MAX_MESSAGES: 10

  dbt-docs:
    build:
      context: ../../DATA OBSERVABILITY
      dockerfile: dockerfile.dbt

    environment:
      DBT_PROFILES_DIR: /app

    command: >
      sh -c "cd construction_elt_project &&
            dbt docs serve --host 0.0.0.0 --port 8080"

    ports:
      - "8081:8080"

  # duckdb-ui:
  #   build:
  #     context: "../../DATA OBSERVABILITY"
  #     dockerfile: dockerfile.dbt
  #   working_dir: /app/construction_elt_project
  #   command: >
  #     sh -c "duckdb -ui dev.duckdb && tail -f /dev/null"
  #   ports:
  #     - "4213:4213"

  construction-dashboard:
    build:
      context: "../construction-dashboard"
      dockerfile: dockerfile
    depends_on:
      - kafka
      - ksqldb
    ports:
      - "8080:8080"
    environment:
      KAFKA_BOOTSTRAP_SERVERS: kafka:29092
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./:/workspace