name: CD

on:
  workflow_run:
    workflows: ["CI"]
    types:
      - completed

permissions:
  contents: read
  packages: write

jobs:
  docker-deploy:
    name: Build and Push Docker Images
    runs-on: ubuntu-latest

    if: ${{ github.event.workflow_run.conclusion == 'success' }}

    steps:
      - name: Checkout data mesh + dashboard repo
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase owner
        run: |
          echo "OWNER_LC=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Set image names
        run: |
          echo "CONSTRUCTION_APP_IMAGE=ghcr.io/${OWNER_LC}/construction-app:latest" >> $GITHUB_ENV
          echo "DASHBOARD_IMAGE=ghcr.io/${OWNER_LC}/construction-dashboard:latest" >> $GITHUB_ENV
          echo "DBT_PIPELINE_IMAGE=ghcr.io/${OWNER_LC}/dbt-pipeline:latest" >> $GITHUB_ENV

      - name: Build and push construction app
        uses: docker/build-push-action@v6
        with:
          context: ./kafka
          file: ./kafka/Dockerfile
          push: true
          tags: ${{ env.CONSTRUCTION_APP_IMAGE }}

      - name: Build and push construction dashboard
        uses: docker/build-push-action@v6
        with:
          context: ./construction-dashboard
          file: ./construction-dashboard/dockerfile
          push: true
          tags: ${{ env.DASHBOARD_IMAGE }}

      - name: Checkout data observability repo
        uses: actions/checkout@v4
        with:
          repository: OSCARYCIJNTJE/Data-observability
          ref: ${{ github.event.workflow_run.head_branch }}
          path: data-observability

      - name: Build and push dbt pipeline
        uses: docker/build-push-action@v6
        with:
          context: ./data-observability
          file: ./data-observability/dockerfile.dbt
          push: true
          tags: ${{ env.DBT_PIPELINE_IMAGE }}